package cli

import (
	"bytes"
	"encoding/json"
	"runtime"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// cobraBuiltins are generated by cobra itself rather than declared in this
// package, so they are documented in the overview topic instead of getting
// their own docTopic.
var cobraBuiltins = map[string]bool{"help": true, "completion": true}

// platformFlagTopics document flags that only exist in a build-tagged variant
// of the command (pid is a /proc reader with a no-flag stub off Linux), so the
// "documented flag must exist" direction cannot apply to them everywhere.
var platformFlagTopics = map[string]string{"pid": "linux"}

// commandTopics indexes the reference by the cobra command each topic covers.
func commandTopics(t *testing.T) map[string]docTopic {
	t.Helper()
	byCommand := make(map[string]docTopic)
	for _, topic := range docTopics() {
		if topic.Command == "" {
			continue
		}
		if prev, dup := byCommand[topic.Command]; dup {
			t.Fatalf("commands %q and %q both document the command %q", prev.Name, topic.Name, topic.Command)
		}
		byCommand[topic.Command] = topic
	}
	return byCommand
}

// registeredCommands returns every subcommand cobra will expose, including the
// ones it generates itself.
func registeredCommands(t *testing.T) []*cobra.Command {
	t.Helper()
	root := newRootCommand()
	root.SetOut(&bytes.Buffer{})
	root.SetErr(&bytes.Buffer{})
	root.SetArgs([]string{"--help"})
	if err := root.Execute(); err != nil {
		t.Fatalf("executing root: %v", err)
	}
	return root.Commands()
}

// TestDocsCoverEveryCommand is the maintenance contract for `gopm docs`: a new
// command without a docTopic fails the build rather than silently shipping a
// reference that lies about what gopm can do.
func TestDocsCoverEveryCommand(t *testing.T) {
	byCommand := commandTopics(t)

	for _, cmd := range registeredCommands(t) {
		name := cmd.Name()
		if cobraBuiltins[name] {
			continue
		}
		if _, ok := byCommand[name]; !ok {
			t.Errorf("command %q has no docs topic — add one in docs_commands_*.go", name)
		}
	}
}

// TestDocsCoverEveryFlag catches the other half of the drift: a flag added to
// an existing command, or removed from one, without touching its topic.
func TestDocsCoverEveryFlag(t *testing.T) {
	byCommand := commandTopics(t)

	for _, cmd := range registeredCommands(t) {
		name := cmd.Name()
		if cobraBuiltins[name] {
			continue
		}
		topic, ok := byCommand[name]
		if !ok {
			continue // reported by TestDocsCoverEveryCommand
		}

		documented := make(map[string]docFlag, len(topic.Flags))
		for _, f := range topic.Flags {
			documented[strings.TrimPrefix(f.Long, "--")] = f
		}

		actual := make(map[string]bool)
		cmd.Flags().VisitAll(func(f *pflag.Flag) {
			if f.Hidden {
				return // deliberately undocumented compatibility aliases
			}
			actual[f.Name] = true

			doc, ok := documented[f.Name]
			if !ok {
				t.Errorf("gopm %s: flag --%s is not documented — add it to the %q topic", name, f.Name, topic.Name)
				return
			}
			wantShort := ""
			if f.Shorthand != "" {
				wantShort = "-" + f.Shorthand
			}
			if doc.Short != wantShort {
				t.Errorf("gopm %s --%s: docs list shorthand %q, cobra has %q", name, f.Name, doc.Short, wantShort)
			}
		})

		if goos, only := platformFlagTopics[topic.Name]; only && runtime.GOOS != goos {
			continue // the flagged build of this command is not compiled here
		}
		for flagName := range documented {
			if !actual[flagName] {
				t.Errorf("gopm %s: docs describe --%s but the command has no such flag", name, flagName)
			}
		}
	}
}

// TestDocsTopicsAreWellFormed guards the parts of a topic that the renderer and
// the `gopm docs <topic>` lookup depend on.
func TestDocsTopicsAreWellFormed(t *testing.T) {
	groups := map[string]bool{
		docGroupConcepts: true, docGroupProcess: true, docGroupDaemon: true,
		docGroupConfig: true, docGroupTool: true,
	}

	seen := make(map[string]bool)
	for _, topic := range docTopics() {
		switch {
		case topic.Name == "":
			t.Fatalf("topic with empty name: %+v", topic)
		case seen[topic.Name]:
			t.Errorf("duplicate docs topic %q", topic.Name)
		case topic.Name != strings.ToLower(topic.Name):
			t.Errorf("topic %q must be lowercase — lookup lowercases the argument", topic.Name)
		case topic.Summary == "":
			t.Errorf("topic %q has no summary", topic.Name)
		case !groups[topic.Group]:
			t.Errorf("topic %q has unknown group %q", topic.Name, topic.Group)
		}
		seen[topic.Name] = true
	}

	// Every cross-reference must resolve, otherwise "See also" sends a reader
	// (or an agent) to a topic that errors out.
	for _, topic := range docTopics() {
		for _, ref := range topic.SeeAlso {
			if !seen[ref] {
				t.Errorf("topic %q references unknown topic %q in SeeAlso", topic.Name, ref)
			}
		}
	}
}

// TestDocsTopicsAreGrouped keeps the reference ordered by group, which both the
// full render and the index rely on to print each heading once.
func TestDocsTopicsAreGrouped(t *testing.T) {
	var order []string
	seen := make(map[string]bool)
	for _, topic := range docTopics() {
		if len(order) == 0 || order[len(order)-1] != topic.Group {
			if seen[topic.Group] {
				t.Errorf("group %q appears in two separate runs of topics", topic.Group)
			}
			order = append(order, topic.Group)
			seen[topic.Group] = true
		}
	}
}

func TestSelectDocTopics(t *testing.T) {
	all := docTopics()

	if got, err := selectDocTopics(all, nil); err != nil || len(got) != len(all) {
		t.Fatalf("no args should select every topic: got %d topics, err %v", len(got), err)
	}

	got, err := selectDocTopics(all, []string{"start", "OVERVIEW"})
	if err != nil {
		t.Fatalf("selecting known topics: %v", err)
	}
	if len(got) != 2 || got[0].Name != "start" || got[1].Name != "overview" {
		t.Errorf("expected [start overview] in request order, got %v", topicNames(got))
	}

	if _, err := selectDocTopics(all, []string{"nope"}); err == nil {
		t.Error("expected an error for an unknown topic")
	}
}

func topicNames(topics []docTopic) []string {
	names := make([]string, len(topics))
	for i, t := range topics {
		names[i] = t.Name
	}
	return names
}

// TestDocsRenderPlainHasNoEscapes matters because the primary consumer is a
// program reading piped output: a stray escape code corrupts the ingest.
func TestDocsRenderPlainHasNoEscapes(t *testing.T) {
	buf := &bytes.Buffer{}
	renderDocs(buf, docPen{on: false}, docTopics(), true)

	if strings.Contains(buf.String(), "\033") {
		t.Error("plain render leaked an ANSI escape sequence")
	}
	for _, want := range []string{"capability reference", "## start", "Usage:", "Flags:", "Examples:"} {
		if !strings.Contains(buf.String(), want) {
			t.Errorf("plain render is missing %q", want)
		}
	}
}

func TestDocsRenderColoredEmitsEscapes(t *testing.T) {
	buf := &bytes.Buffer{}
	renderDocs(buf, docPen{on: true}, []docTopic{docTopicStart()}, false)

	if !strings.Contains(buf.String(), "\033[") {
		t.Error("colored render emitted no ANSI escape sequences")
	}
}

func TestNewDocPen(t *testing.T) {
	// os.Stdout under `go test` is a pipe, so auto must resolve to plain.
	cases := []struct {
		mode    string
		want    bool
		wantErr bool
	}{
		{mode: "always", want: true},
		{mode: "never", want: false},
		{mode: "auto", want: false},
		{mode: "", want: false},
		{mode: "sometimes", wantErr: true},
	}
	for _, tc := range cases {
		pen, err := newDocPen(tc.mode, nil)
		if tc.wantErr {
			if err == nil {
				t.Errorf("--color %q should be rejected", tc.mode)
			}
			continue
		}
		if err != nil {
			t.Errorf("--color %q: unexpected error %v", tc.mode, err)
			continue
		}
		if pen.on != tc.want {
			t.Errorf("--color %q: color on = %v, want %v", tc.mode, pen.on, tc.want)
		}
	}
}

// TestDocsJSONRoundTrips protects the --json contract that agents parse.
func TestDocsJSONRoundTrips(t *testing.T) {
	data, err := json.Marshal(docsPayload{Version: "test", Topics: docTopics()})
	if err != nil {
		t.Fatalf("marshalling docs: %v", err)
	}

	var decoded docsPayload
	if err := json.Unmarshal(data, &decoded); err != nil {
		t.Fatalf("unmarshalling docs: %v", err)
	}
	if decoded.Version != "test" || len(decoded.Topics) != len(docTopics()) {
		t.Fatalf("round trip lost data: version %q, %d topics", decoded.Version, len(decoded.Topics))
	}
	if decoded.Topics[0].Name != docTopics()[0].Name {
		t.Errorf("topic order changed: %q != %q", decoded.Topics[0].Name, docTopics()[0].Name)
	}
}

func TestWrapIndent(t *testing.T) {
	lines := wrapIndent("alpha beta gamma delta", 14, "  - ", "    ")
	want := []string{"  - alpha beta", "    gamma", "    delta"}
	if len(lines) != len(want) {
		t.Fatalf("got %d lines %q, want %d", len(lines), lines, len(want))
	}
	for i := range want {
		if lines[i] != want[i] {
			t.Errorf("line %d = %q, want %q", i, lines[i], want[i])
		}
	}

	// Pre-formatted blocks (JSON samples, multi-line recipes) keep their shape.
	block := wrapIndent("{\n  \"a\": 1\n}", 10, "", "")
	if len(block) != 3 || block[1] != `  "a": 1` {
		t.Errorf("multi-line input was re-wrapped: %q", block)
	}
}

func TestFlagSpecAlignsLongFlags(t *testing.T) {
	if got := flagSpec(docFlag{Long: "--lines", Short: "-n", Arg: "<n>"}); got != "-n, --lines <n>" {
		t.Errorf("flagSpec with shorthand = %q", got)
	}
	if got := flagSpec(docFlag{Long: "--err"}); got != "    --err" {
		t.Errorf("flagSpec without shorthand = %q, want it padded to align", got)
	}
}
